---
# tasks file for deploy_web_server
- name: install modules
  apt:
    name: "{{item}}"
    state: latest
  with_items:
    - python-apt
    - python3-apt
    - git

- name: add key for install nginx
  apt_key:
    url: https://nginx.org/packages/keys/nginx_signing.key
    state: present

- apt_repository:
    repo: deb http://nginx.org/packages/debian/ stretch nginx
    state: present

- name: add key for dotdeb
  apt_key:
    url: https://dotdeb.org/dotdeb.gpg
    state: present

- apt_repository:
    repo: deb http://packages.dotdeb.org stretch all
    state: present

- name: update
  apt:
   update_cache: yes

- name: install nginx
  apt: name=nginx state=latest

- name: install apache
  apt: name=apache2 state=latest

- name: install apache module
  apt: name=libapache2-mpm-itk state=latest

- apache2_module:
    state: present
    name: "{{item}}"
  with_items:
    - mpm_prefork
    - mpm_itk

- name: install php
  apt: name=php state=latest

- name: install mysql
  apt: name=mysql-server state=latest

- name: make ports.conf in apache
  template:
    src: /root/Projects/vagrant-ansible/roles/deploy_web_server/templates/ports.j2
    dest: /etc/apache2/ports.conf

- name: make apache virtualhosts configuration
  template:
    src: /root/Projects/vagrant-ansible/roles/deploy_web_server/templates/apache_siteconf1.j2
    dest: /etc/apache2/sites-available/test1.local.conf

- name: make apache virtualhosts configuration
  template:
    src: /root/Projects/vagrant-ansible/roles/deploy_web_server/templates/apache_siteconf2.j2
    dest: /etc/apache2/sites-available/test2.local.conf

- service:
     name: apache2
     state: restarted

- name: make nginx.conf
  template:
    src: /root/Projects/vagrant-ansible/roles/deploy_web_server/templates/nginx.j2
    dest: /etc/nginx/nginx.conf

- name: make directory for virtualhosts nginx
  file:
     dest: /etc/nginx/sites-available
     state: directory

- name: make directory for virtualhosts nginx
  file:
     dest: /etc/nginx/sites-enabled
     state: directory

- name: make directory for virtualhosts nginx
  file:
     dest: /etc/nginx/templates
     state: directory

- name: make apache24.conf
  template:
    src: /root/Projects/vagrant-ansible/roles/deploy_web_server/templates/apache24.j2
    dest: /etc/nginx/templates/apache24.conf

- name: make descriprion for test1.local
  template:
    src: /root/Projects/vagrant-ansible/roles/deploy_web_server/templates/nginx_site_description1.j2
    dest: /etc/nginx/sites-available/test1.local.conf

- name: make descriprion for test2.local
  template:
    src: /root/Projects/vagrant-ansible/roles/deploy_web_server/templates/nginx_site_description2.j2
    dest: /etc/nginx/sites-available/test2.local.conf

- name: connect the nginx configuration file test1.local
  file:
     src: /etc/nginx/sites-available/test1.local.conf
     dest: /etc/nginx/sites-enabled/test1.local.conf
     state: link

- name: connect the nginx configuration file test2.local
  file:
     src: /etc/nginx/sites-available/test2.local.conf
     dest: /etc/nginx/sites-enabled/test2.local.conf
     state: link

- name: connect the apache configuration file test1.local
  file:
     src: /etc/apache2/sites-available/test1.local.conf
     dest: /etc/apache2/sites-enabled/test1.local.conf
     state: link

- name: connect the apache configuration file test2.local
  file:
     src: /etc/apache2/sites-available/test2.local.conf
     dest: /etc/apache2/sites-enabled/test2.local.conf
     state: link

- name: unconnect the apache's default configuration file
  file:
     dest: /etc/apache2/sites-enabled/000-default.conf
     state: absent

- name: change php.ini
  lineinfile:
    dest: /etc/php/7.0/apache2/php.ini
    regexp: '^memory_limit '
    insertafter: '^#memory_limit '
    line: 'memory_limit = 256M'

- name: change mysql configuration
  blockinfile:
     dest: /etc/mysql/my.cnf
     content: |
           max_connections = 700

- name: make group for isolation hosts
  group:
     name: www-data2
     state: present

- name: make user for isolation hosts
  user:
     name: www-data2
     state: present


- name: make host directory
  file:
     dest: /var/www/html/test1.local
     state: directory
     owner: www-data2
     group: www-data2

- name: make host directory
  file:
     dest: /var/www/html/test2.local
     state: directory

- git:
    repo: https://github.com/joomla/joomla-cms.git
    dest: /var/www/html/test1.local

- git:
    repo: https://github.com/joomla/joomla-cms.git
    dest: /var/www/html/test2.local

- service:
     name: nginx
     state: restarted
- service:
     name: apache2
     state: restarted
